name: fullvisionfilms
favicon: null
layout_spectrum: 0.6216307135764509
typography_spectrum: 0.18502347427420318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1b19'
    - '#97866f'
    - '#50493e'
    - '#f8c08f'
    - '#ffffff'
  brandStrength: 0.9125462032388896
  lightness: 0.8332522413693368
  saturation: 0.2673753774724901
  rhythmicContrast: 0.7838779166340828
purpose: []
